webtoon/urls.py
from django.urls import path
from django.shortcuts import redirect

from webtoon.views import WebtoonView
from webtoon.views import BookmarkView
from webtoon.views import bookmark_check


def index(request):
    return redirect('list/')


app_name = 'webtoon'

urlpatterns = [
    path('', index,),
    path('list/', WebtoonView.as_view(), name='list'),
    path('bookmark/', BookmarkView.as_view(), name='bookmark'),
    path('check/', bookmark_check, name='check',),
]

webtoon/models.py
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.conf import settings

# 웹툰 파일명으로 이미지 저장
def webtoon_img_path(instance, filename):
    """웹툰 파일명으로 이미지 저장"""
    # Rename the file to its name.
    return 'webtoon/{0}.jpg'.format(instance.webtoon_name)

# 파일저장시 관리 클래스
class OverwriteStorage(FileSystemStorage):
    """파일저장시 관리 클래스"""
    def get_available_name(self, name, max_length=None):
        """이미 있는 파일의 경우 삭제후 저장"""
        # If the file already exists, delete it so it can be replaced.
        print(self, name, max_length)
        if self.exists(name):
            self.delete(name)
        return name

# 작가 테이블
class AutherModel(models.Model):
    """
    작가 모델
    id : pk 값
    auther_name : 이름
    auther_create_time : 생성일
    """
    class Meta:
        app_label = 'webtoon'
        verbose_name = '작가'
        verbose_name_plural = '작가 리스트'

    auther_name = models.CharField(
        max_length=100,
        verbose_name='이름',
    )
    auther_create_time = models.DateTimeField(
        verbose_name='생성일',
        auto_now_add=True,
    )
    def __str__(self,) -> str:
        return format(self.auther_name)

# 연재일 테이블
class DayModel(models.Model):
    """ 
    연재일 모델 
    id : pk 값
    day_name : 연재일
    day_create_time : 생성일
    """
    class Meta:
        app_label = 'webtoon'
        verbose_name = '연재일'
        verbose_name_plural = '연재일 리스트'

    day_name = models.CharField(
        max_length=3,
        verbose_name='연재일',
    )
    day_create_time = models.DateTimeField(
        verbose_name='생성일',
        auto_now_add=True,
    )

    def __str__(self,) -> str:
        return format(self.day_name)

# 태그 테이블
class TagModel(models.Model):
    """
    태그 모델
    id : pk 값
    tag_name : 태그 명
    tag_create_time : 태그 생성일
    WebtoonModels_set : 웹툰과 n:m 관계
    """
    class Meta:
        app_label = 'webtoon'
        verbose_name = '태그'
        verbose_name_plural = '태그 리스트'

    tag_name = models.CharField(
        max_length=10,
        verbose_name='태그',
        unique=True,
    )
    tag_create_time = models.DateTimeField(
        verbose_name='생성일',
        auto_now_add=True,
    )

    def __str__(self,) -> str:
        return format(self.tag_name)

# 웹툰 테이블
class WebtoonModel(models.Model):
    """
    웹툰 모델
    id : pk 값
    webtoon_name : 웹툰
    webtoon_description : 설명
    webtoon_tag : 태그
    webtoon_auther : 작가
    webtoon_link : 링크
    webtoon_img : 이미지
    webtoon_end : 완결여부 True:완결, False:연재(default)
    webtoon_day : 연재일
    webtoon_adult : 성인여부  True:성인, False:전체(default)
    webtoon_create_time :생성일   
    """
    class Meta:
        app_label = 'webtoon'
        verbose_name = '웹툰'
        verbose_name_plural = '웹툰 리스트'

    webtoon_name = models.CharField(
        max_length=100,
        verbose_name='웹툰',
        unique=True,
    )
    webtoon_description = models.CharField(
        max_length=1000,
        verbose_name='설명',
        null=True,
        blank=True,
    )
    webtoon_tag = models.ManyToManyField(
        TagModel,
        verbose_name='태그',
        blank=True,
    )
    webtoon_auther = models.ManyToManyField(
        AutherModel,
        verbose_name='작가',
        blank=True,
    )
    webtoon_link = models.CharField(
        max_length=500,
        verbose_name='링크',
        null=True,
        blank=True,
    )
    webtoon_img = models.ImageField(
        upload_to=webtoon_img_path,
        storage=OverwriteStorage,
        verbose_name='이미지',
        null=True,
        blank=True,
    )
    webtoon_end = models.BooleanField(
        verbose_name='완결',
        default=False,
    )
    webtoon_day = models.ForeignKey(
        'DayModel',
        verbose_name='연재일',
        on_delete=models.DO_NOTHING,
        null=True,
        blank=True,
    )
    webtoon_adult = models.BooleanField(
        verbose_name='성인',
        default=False,
    )
    webtoon_create_time = models.DateTimeField(
        verbose_name='생성일',
        auto_now_add=True,
    )


    def __str__(self,) -> str:
        return format(self.webtoon_name)

    def get_auther(self,) -> str:
        return ", ".join([obj.auther_name for obj in self.webtoon_auther.all()])
    get_auther.short_description = '작가'

    def get_tag(self,) -> str:
        return ", ".join([obj.tag_name for obj in self.webtoon_tag.all()])
    get_tag.short_description = '태그'

    def get_image_url(self):
        return '%s%s' % (settings.MEDIA_URL, self.webtoon_img)


class BookmarkModel(models.Model):
    """
    유저별 북마크 모델
    id : pk 값
    user_info : 유저uuid명
    bookmark_webtoon : 유저와 웹툰 n:m
    user_create_time : 생성일자
    """
    class Meta:
        app_label = 'webtoon'
        verbose_name = '북마크'
        verbose_name_plural = '유저별 북마크'

    user_info = models.CharField(
        max_length=255,
        verbose_name='유저식별값'
    )
    bookmark_webtoon = models.ManyToManyField(
        WebtoonModel,
        verbose_name='북마크',
        blank=True,
    )
    user_create_time = models.DateTimeField(
        verbose_name='생성일',
        auto_now_add=True,
    )

    def __str__(self,) -> str:
        return format(self.user_info)

    def get_bookmark(self,) -> str:
        return ", ".join([obj.webtoon_name for obj in self.bookmark_webtoon.all()])

    get_bookmark.short_description = '북마크 목록'

webtoon/views.py
import uuid
from typing import Any
from django.http import HttpRequest, HttpResponse, HttpResponseNotAllowed
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic import View
from django.db.models import Q
from django.core.paginator import Paginator
from webtoon.models import WebtoonModel
from webtoon.models import AutherModel
from webtoon.models import DayModel
# from webtoon.models import PublishingModel
from webtoon.models import TagModel
from webtoon.models import BookmarkModel

# Create your views here.

from django.http import JsonResponse


class WebtoonView(ListView):
    model = WebtoonModel
    template_name = 'list.html'
    context_object_name = 'webtoon_list'
    paginate_by = 20  # 한 페이지에 보여줄 오브젝트의 갯수

    def get_context_data(self, **kwargs):
        # 추가적인 데이터(DB에 있는것)를 추가할때 사용
        context = super().get_context_data(**kwargs)

        # 연재일 데이터
        context['day_list'] = DayModel.objects.all()
        # 선택한 연재일
        context['day_select'] = self.request.GET.get('day')

        # 연재상태
        context['status'] = self.request.GET.get('status')

        # 태그 데이터
        context['tag_list'] = TagModel.objects.all()
        # 선택한 태그
        context['tag_select'] = self.request.GET.get('tag')

        context['search'] = self.request.GET.get('search')
        # 유저의 북마크 정보 표기
        user_info = self.request.COOKIES.get("user_info")
        if user_info:
            try:
                bookmark = BookmarkModel.objects.get(user_info=user_info)
            except BookmarkModel.DoesNotExist:
                context['user_info'] = list()
            else:
                context['user_info'] = bookmark.bookmark_webtoon.all()

        return context

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        response = super().get(request, *args, **kwargs)
        # 첫 접속자의 경우 신규 id 발급
        if not request.COOKIES.get('user_info'):
            user_info = str(uuid.uuid4())
            response.set_cookie('user_info', user_info)
            BookmarkModel(
                user_info=user_info,
            ).save()

        return response

    def get_queryset(self):
        queryset = super().get_queryset()

        # url의 쿼리스트링 분석
        day = self.request.GET.get('day')
        status = self.request.GET.get('status')
        tag = self.request.GET.get('tag')
        search = self.request.GET.get('search')

        if status == "1":
            queryset = queryset.filter(webtoon_end=False,
                                       webtoon_adult=False)
        elif status == "2":
            queryset = queryset.filter(webtoon_end=False,
                                       webtoon_adult=True)
        elif status == "3":
            queryset = queryset.filter(webtoon_end=True)

        if day:
            if day != "0":
                dayM = DayModel.objects.get(day_name=day)
                queryset = queryset.filter(webtoon_day=dayM)
        if tag:
            if tag != "0":
                tagquery = TagModel.objects.get(pk=tag)
                queryset = queryset.filter(webtoon_tag=tagquery)

        if search:
            queryset = queryset.filter(
                Q(webtoon_name__icontains=search)).distinct()

        return queryset


class BookmarkView(ListView):
    model = BookmarkModel
    template_name = 'bookmark.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        # 연재상태
        status = self.request.GET.get('status')
        context['status'] = status
        # 태그 데이터
        context['tag_list'] = TagModel.objects.all()
        # 선택한 태그
        tag_select = self.request.GET.get('tag')
        context['tag_select'] = tag_select

        # 유저 id를 통해 북마크 정보를 조회
        if user_info := self.request.COOKIES.get('user_info'):
            user, _ = BookmarkModel.objects.get_or_create(user_info=user_info)
            queryset = user.bookmark_webtoon.all()

            if status == "1":
                queryset = user.bookmark_webtoon.filter(webtoon_end=False,
                                                        webtoon_adult=False)
            elif status == "2":
                queryset = user.bookmark_webtoon.filter(webtoon_end=False,
                                                        webtoon_adult=True)
            elif status == "3":
                queryset = user.bookmark_webtoon.filter(
                    webtoon_end=True)
            else:
                queryset = user.bookmark_webtoon.all()

            if tag_select:
                if tag_select != '0':
                    tagquery = TagModel.objects.get(pk=tag_select)
                    queryset = queryset.filter(
                        webtoon_tag=tagquery)
                else:
                    queryset = queryset.all()
            else:
                queryset = user.bookmark_webtoon.all()

            # 검색
            if search := self.request.GET.get('search'):
                context['search'] = search
                queryset = queryset.filter(
                    Q(webtoon_name__icontains=search)).distinct()

            # 페이징
            if page_select := self.request.GET.get('page'):
                paginator = Paginator(queryset, 10)
                page_info = paginator.get_page(page_select)
                context['page_obj'] = page_info
                queryset = page_info.object_list

            context['bookmark'] = queryset
        return context


def bookmark_check(request):
    # 북마크 버튼 누를시 유저 id 에 북마크 기록 저장
    webtoon_id = request.POST.get("bookmark")
    user_info = request.COOKIES.get('user_info')
    method = request.POST.get("check")
    if webtoon_id and user_info:
        webtoon = WebtoonModel.objects.get(pk=webtoon_id)
        user = BookmarkModel.objects.get(user_info=user_info)
        if method == 'true':
            user.bookmark_webtoon.add(webtoon)
        else:
            user.bookmark_webtoon.remove(webtoon)
        user.save()
    return redirect(reverse('webtoon:list'))

webtoon/templates/bookmark.html
{% extends "template/base.html" %}
{% load static %}


{% block search %}
<form class="offset-md-8" role="search" method="get">
    <input name="search" 
    type="search" 
    class="form-control form-control-dark"
    value="{{ search|default_if_none:'' }}"
    placeholder="제목검색" aria-label="찾다">
</form>
{% endblock %}

{% block nav %}
{% include "template/nav.html" with status=status %}
{% endblock %}


{% block tag %}
{% include "template/tag.html" with tags=tag_list tagstatus=tag %}
{% endblock %}
{% block list %}

{% if bookmark %}
<div class="container">
    <div class="row row-cols-2">
        <!-- 리스트 하나 표기하는 규격 start -->
        {% for webtoon in bookmark %}
    
        <div class="row mb-2"style="min-width: 650px;">
            <div class="col-md col-auto ">
                <img class="max-size" src="{{ webtoon.webtoon_img.url }}" alt="웹툰이미지" style="min-height: 500px;" >
            </div>
    
            <div class="col-md col-auto">
                <h3 class="mb-1"><strong class=" mb-2 fs-5">{{ webtoon.webtoon_name }}</strong></h3>
                <div class="mb-1 text-muted row row-cols-auto">
                    <div  class="col back border rounded-3 mx-1" >
                        {% if webtoon.webtoon_end  %}
                        완결
                        {% else %}
                        연재중
                        {% endif %}
                    </div>
                    <div class="col back border rounded-3 mx-1" >{{ webtoon.webtoon_day }}</div>
                        {% if webtoon in user_info %}
                        <button type="button" value="{{webtoon.id}}" class=" mx-1 bookmark bookmark-on btn btn-outline-secondary  btn-sm">
                            북마크
                        </button>
                        <a target="_blank" class="mx-1 bookmark bookmark-on btn btn-outline-secondary  btn-sm" href="{{ webtoon.webtoon_link }}">보기</a>
                        {% else %}
                        <button type="button" value="{{webtoon.id}}" class="  bookmark btn btn-secondary btn-sm">
                            북마크
                        </button>
                        <a target="_blank" class="mx-1 bookmark bookmark-on btn btn-outline-secondary  btn-sm" href="{{ webtoon.webtoon_link }}">보기</a>
                        
                        {% endif %}
                </div>
                <div class="row-cols-auto row my-1">
                    {% for tag in webtoon.webtoon_tag.all %}
                        <div class="col me-1 border border-dark-subtle rounded-pill ">{{ tag.tag_name }}</div>
                    {% endfor %}
                </div>
                <div class="mb-5">
                    {{ webtoon.webtoon_auther.all|join:", " }}
                </div>
                <p class="text-justify mb-4">
                    {{ webtoon.webtoon_description|slice:"230" }}{% if webtoon.webtoon_description|length > 300 %}...{% endif %}
                </p>
               
            </div>
        </div>
        {% endfor %}
    
    </div>
</div>

{% else %}
<div class="text-center">북마크 하신게 없답니다.</div>
{% endif %}

{% endblock %}


{% block page  %}
<ul class="mt-5 pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if page_obj.has_previous %}
    <li class="page-item">
        <button class="page-link page" type="button" value="{{ page_obj.previous_page_number }}" >이전</button>
    </li>
    {% else %}
    <li class="page-item disabled">
        <button class="page-link" type="button" >이전</button>
    </li>
    {% endif %}

    <!-- 페이지리스트 -->
    {% for page_number in page_obj.paginator.page_range %}
    {% if page_number >= page_obj.number|add:-5 and page_number <= page_obj.number|add:5 %}
    {% if page_number == page_obj.number %}
    <li class="page-item active" aria-current="page">
        <button class="page-link page" type="button" value="{{ page_number }}" >{{ page_number }}</button>
    </li>
    {% else %}
    <li class="page-item">
        <button class="page-link page" type="button" value="{{ page_number }}" >{{ page_number }}</button>
    </li>
    {% endif %}
    {% endif %}
    {% endfor %}

    <!-- 다음페이지 -->
    {% if page_obj.has_next %}
    <li class="page-item">
        <button class="page-link page" type="button" value="{{ page_obj.next_page_number }}" >다음</button>
    </li>
    {% else %}
    <li class="page-item disabled">
        <button class="page-link" type="button">다음</button>
    </li>
    {% endif %}
</ul>
{% endblock %}

{% block script_bottom %} 
<script>

    $(document).ready(function() {
      $('.bookmark').click(function() {
        var webtoon_id = $(this).val();
        var check = $(this).hasClass('bookmark-on');
    
        $.ajax({
          type: 'POST',
          url: '{% url "webtoon:check" %}',
          data: {
            'bookmark': webtoon_id,
            'check': check,
          },
          headers: {
            'X-CSRFToken': '{{ csrf_token }}'
          },
        });
    
        $(this).toggleClass('btn-secondary');
        $(this).toggleClass('btn-outline-secondary');
        $(this).toggleClass('bookmark-on');
      });
    });
</script>
{% endblock %}

webtoon/templates/list.html
{% extends "template/base.html" %}
{% load static %}

{% block script_top %} 
{% endblock %}

{% block search %}
<form class="offset-md-8" role="search" method="get">
    <input name="search" 
    type="search" 
    class="form-control form-control-dark"
    value="{{ search|default_if_none:'' }}"
    placeholder="제목검색" aria-label="찾다">
</form>
{% endblock %}

{% block nav %}
    {% include "template/nav.html" with status=status %}
{% endblock %}

{% block day %}
    {% include "template/day.html" with days=day_list day_select=day_select %}
{% endblock %}


 
{% block publishing %}
<!-- {% include "template/publishing.html" with publishings=publishing_list %} -->
{% endblock %} 


{% block tag %}
    {% include "template/tag.html" with tags=tag_list tag_select=tag_select %}
{% endblock %}

{% block list %}


<div id="listshow">
    <div class="row row-cols-4 justify-content-center">
        {% if webtoon_list %}
        {% for webtoon in webtoon_list %}
        <div class="card mx-1 px-0" style="width: 18rem;">
            <img src="{{ webtoon.webtoon_img.url }}" class="card-img-top" alt="웹툰이미지" style="min-height: 500px;">
            <div class="card-body">
                <h5 class="card-title">
                    <strong class=" mb-2 fs-5">
                        {{ webtoon.webtoon_name }}
                    </strong>
                </h5>
                
                <div class="cut-letter pb-1 ">
                    {% for auther in webtoon.webtoon_auther.all %}
                    {{ auther.auther_name }}
                    {% endfor %}
                </div>

                <div class="row row-cols-auto">
                    {% for tag in webtoon.webtoon_tag.all|slice:":3" %}
                        <div class="col ms-1 border border-dark-subtle rounded-pill">{{ tag.tag_name }}</div>
                    {% endfor %}
                </div>
            </div>
            <div class="row px-4">
                <a class="col btn btn-secondary btn-sm mb-2 me-2  " target="_blank" href="{{ webtoon.webtoon_link }}">보러가기</a>
                {% if webtoon in user_info %}
                <button type="button" value="{{webtoon.id}}" class=" col bookmark btn btn-secondary btn-sm mb-2 ">
                    북마크
                </button>
                {% else %}
                <button type="button" value="{{webtoon.id}}" class=" col bookmark bookmark-on btn btn-outline-secondary  btn-sm mb-2 ">
                    북마크
                </button>
                {% endif %}
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div>자료가 없습니다.</div>
        
        {% endif %}

    </div>
</div>
{% endblock %}

{% block page  %}
<ul class="mt-5 pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if page_obj.has_previous %}
    <li class="page-item">
        <button class="page-link page" type="button" value="{{ page_obj.previous_page_number }}" >이전</button>
    </li>
    {% else %}
    <li class="page-item disabled">
        <button class="page-link" type="button" >이전</button>
    </li>
    {% endif %}

    <!-- 페이지리스트 -->
    {% for page_number in page_obj.paginator.page_range %}
    {% if page_number >= page_obj.number|add:-5 and page_number <= page_obj.number|add:5 %}
    {% if page_number == page_obj.number %}
    <li class="page-item active" aria-current="page">
        <button class="page-link page" type="button" value="{{ page_number }}" >{{ page_number }}</button>
    </li>
    {% else %}
    <li class="page-item">
        <button class="page-link page" type="button" value="{{ page_number }}" >{{ page_number }}</button>
    </li>
    {% endif %}
    {% endif %}
    {% endfor %}

    <!-- 다음페이지 -->
    {% if page_obj.has_next %}
    <li class="page-item">
        <button class="page-link page" type="button" value="{{ page_obj.next_page_number }}" >다음</button>
    </li>
    {% else %}
    <li class="page-item disabled">
        <button class="page-link" type="button">다음</button>
    </li>
    {% endif %}
</ul>
{% endblock %}

{% block script_bottom %} 
<script>

$(document).ready(function() {
  $('.bookmark').click(function() {
    var webtoon_id = $(this).val();
    var check = $(this).hasClass('bookmark-on');

    $.ajax({
      type: 'POST',
      url: '{% url "webtoon:check" %}',
      data: {
        'bookmark': webtoon_id,
        'check': check,
      },
      headers: {
        'X-CSRFToken': '{{ csrf_token }}'
      },
    });

    $(this).toggleClass('btn-secondary');
    $(this).toggleClass('btn-outline-secondary');
    $(this).toggleClass('bookmark-on');
  });
});

    </script>
{% endblock %}