webtoon/urls.py
from django.urls import path
from django.shortcuts import redirect

from webtoon.views import WebtoonView
from webtoon.views import BookmarkView
from webtoon.views import bookmark_check


def index(request):
    return redirect('list/')


app_name = 'webtoon'

urlpatterns = [
    path('', index,),
    path('list/', WebtoonView.as_view(), name='list'),
    path('bookmark/', BookmarkView.as_view(), name='bookmark'),
    path('check/', bookmark_check, name='check',),
]

webtoon/models.py
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.conf import settings

# 웹툰 파일명으로 이미지 저장
def webtoon_img_path(instance, filename):
    """웹툰 파일명으로 이미지 저장"""
    # Rename the file to its name.
    return 'webtoon/{0}.jpg'.format(instance.webtoon_name)

# 파일저장시 관리 클래스
class OverwriteStorage(FileSystemStorage):
    """파일저장시 관리 클래스"""
    def get_available_name(self, name, max_length=None):
        """이미 있는 파일의 경우 삭제후 저장"""
        # If the file already exists, delete it so it can be replaced.
        print(self, name, max_length)
        if self.exists(name):
            self.delete(name)
        return name

# 작가 테이블
class AutherModel(models.Model):
    """
    작가 모델
    id : pk 값
    auther_name : 이름
    auther_create_time : 생성일
    """
    class Meta:
        app_label = 'webtoon'
        verbose_name = '작가'
        verbose_name_plural = '작가 리스트'

    auther_name = models.CharField(
        max_length=100,
        verbose_name='이름',
    )
    auther_create_time = models.DateTimeField(
        verbose_name='생성일',
        auto_now_add=True,
    )
    def __str__(self,) -> str:
        return format(self.auther_name)

# 연재일 테이블
class DayModel(models.Model):
    """ 
    연재일 모델 
    id : pk 값
    day_name : 연재일
    day_create_time : 생성일
    """
    class Meta:
        app_label = 'webtoon'
        verbose_name = '연재일'
        verbose_name_plural = '연재일 리스트'

    day_name = models.CharField(
        max_length=3,
        verbose_name='연재일',
    )
    day_create_time = models.DateTimeField(
        verbose_name='생성일',
        auto_now_add=True,
    )

    def __str__(self,) -> str:
        return format(self.day_name)

# 태그 테이블
class TagModel(models.Model):
    """
    태그 모델
    id : pk 값
    tag_name : 태그 명
    tag_create_time : 태그 생성일
    WebtoonModels_set : 웹툰과 n:m 관계
    """
    class Meta:
        app_label = 'webtoon'
        verbose_name = '태그'
        verbose_name_plural = '태그 리스트'

    tag_name = models.CharField(
        max_length=10,
        verbose_name='태그',
        unique=True,
    )
    tag_create_time = models.DateTimeField(
        verbose_name='생성일',
        auto_now_add=True,
    )

    def __str__(self,) -> str:
        return format(self.tag_name)

# 웹툰 테이블
class WebtoonModel(models.Model):
    """
    웹툰 모델
    id : pk 값
    webtoon_name : 웹툰
    webtoon_description : 설명
    webtoon_tag : 태그
    webtoon_auther : 작가
    webtoon_link : 링크
    webtoon_img : 이미지
    webtoon_end : 완결여부 True:완결, False:연재(default)
    webtoon_day : 연재일
    webtoon_adult : 성인여부  True:성인, False:전체(default)
    webtoon_create_time :생성일   
    """
    class Meta:
        app_label = 'webtoon'
        verbose_name = '웹툰'
        verbose_name_plural = '웹툰 리스트'

    webtoon_name = models.CharField(
        max_length=100,
        verbose_name='웹툰',
        unique=True,
    )
    webtoon_description = models.CharField(
        max_length=1000,
        verbose_name='설명',
        null=True,
        blank=True,
    )
    webtoon_tag = models.ManyToManyField(
        TagModel,
        verbose_name='태그',
        blank=True,
    )
    webtoon_auther = models.ManyToManyField(
        AutherModel,
        verbose_name='작가',
        blank=True,
    )
    webtoon_link = models.CharField(
        max_length=500,
        verbose_name='링크',
        null=True,
        blank=True,
    )
    webtoon_img = models.ImageField(
        upload_to=webtoon_img_path,
        storage=OverwriteStorage,
        verbose_name='이미지',
        null=True,
        blank=True,
    )
    webtoon_end = models.BooleanField(
        verbose_name='완결',
        default=False,
    )
    webtoon_day = models.ForeignKey(
        'DayModel',
        verbose_name='연재일',
        on_delete=models.DO_NOTHING,
        null=True,
        blank=True,
    )
    webtoon_adult = models.BooleanField(
        verbose_name='성인',
        default=False,
    )
    webtoon_create_time = models.DateTimeField(
        verbose_name='생성일',
        auto_now_add=True,
    )


    def __str__(self,) -> str:
        return format(self.webtoon_name)

    def get_auther(self,) -> str:
        return ", ".join([obj.auther_name for obj in self.webtoon_auther.all()])
    get_auther.short_description = '작가'

    def get_tag(self,) -> str:
        return ", ".join([obj.tag_name for obj in self.webtoon_tag.all()])
    get_tag.short_description = '태그'

    def get_image_url(self):
        return '%s%s' % (settings.MEDIA_URL, self.webtoon_img)


class BookmarkModel(models.Model):
    """
    유저별 북마크 모델
    id : pk 값
    user_info : 유저uuid명
    bookmark_webtoon : 유저와 웹툰 n:m
    user_create_time : 생성일자
    """
    class Meta:
        app_label = 'webtoon'
        verbose_name = '북마크'
        verbose_name_plural = '유저별 북마크'

    user_info = models.CharField(
        max_length=255,
        verbose_name='유저식별값'
    )
    bookmark_webtoon = models.ManyToManyField(
        WebtoonModel,
        verbose_name='북마크',
        blank=True,
    )
    user_create_time = models.DateTimeField(
        verbose_name='생성일',
        auto_now_add=True,
    )

    def __str__(self,) -> str:
        return format(self.user_info)

    def get_bookmark(self,) -> str:
        return ", ".join([obj.webtoon_name for obj in self.bookmark_webtoon.all()])

    get_bookmark.short_description = '북마크 목록'

webtoon/views.py
import uuid
from typing import Any
from django.http import HttpRequest, HttpResponse, HttpResponseNotAllowed
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic import View
from django.db.models import Q
from django.core.paginator import Paginator
from webtoon.models import WebtoonModel
from webtoon.models import AutherModel
from webtoon.models import DayModel
# from webtoon.models import PublishingModel
from webtoon.models import TagModel
from webtoon.models import BookmarkModel

# Create your views here.

from django.http import JsonResponse


class WebtoonView(ListView):
    model = WebtoonModel
    template_name = 'list.html'
    context_object_name = 'webtoon_list'
    paginate_by = 20  # 한 페이지에 보여줄 오브젝트의 갯수

    def get_context_data(self, **kwargs):
        # 추가적인 데이터(DB에 있는것)를 추가할때 사용
        context = super().get_context_data(**kwargs)

        # 연재일 데이터
        context['day_list'] = DayModel.objects.all()
        # 선택한 연재일
        context['day_select'] = self.request.GET.get('day')

        # 연재상태
        context['status'] = self.request.GET.get('status')

        # 태그 데이터
        context['tag_list'] = TagModel.objects.all()
        # 선택한 태그
        context['tag_select'] = self.request.GET.get('tag')

        context['search'] = self.request.GET.get('search')
        # 유저의 북마크 정보 표기
        user_info = self.request.COOKIES.get("user_info")
        if user_info:
            try:
                bookmark = BookmarkModel.objects.get(user_info=user_info)
            except BookmarkModel.DoesNotExist:
                context['user_info'] = list()
            else:
                context['user_info'] = bookmark.bookmark_webtoon.all()

        return context

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        response = super().get(request, *args, **kwargs)
        # 첫 접속자의 경우 신규 id 발급
        if not request.COOKIES.get('user_info'):
            user_info = str(uuid.uuid4())
            response.set_cookie('user_info', user_info)
            BookmarkModel(
                user_info=user_info,
            ).save()

        return response

    def get_queryset(self):
        queryset = super().get_queryset()

        # url의 쿼리스트링 분석
        day = self.request.GET.get('day')
        status = self.request.GET.get('status')
        tag = self.request.GET.get('tag')
        search = self.request.GET.get('search')

        if status == "1":
            queryset = queryset.filter(webtoon_end=False,
                                       webtoon_adult=False)
        elif status == "2":
            queryset = queryset.filter(webtoon_end=False,
                                       webtoon_adult=True)
        elif status == "3":
            queryset = queryset.filter(webtoon_end=True)

        if day:
            if day != "0":
                dayM = DayModel.objects.get(day_name=day)
                queryset = queryset.filter(webtoon_day=dayM)
        if tag:
            if tag != "0":
                tagquery = TagModel.objects.get(pk=tag)
                queryset = queryset.filter(webtoon_tag=tagquery)

        if search:
            queryset = queryset.filter(
                Q(webtoon_name__icontains=search)).distinct()

        return queryset


class BookmarkView(ListView):
    model = BookmarkModel
    template_name = 'bookmark.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        # 연재상태
        status = self.request.GET.get('status')
        context['status'] = status
        # 태그 데이터
        context['tag_list'] = TagModel.objects.all()
        # 선택한 태그
        tag_select = self.request.GET.get('tag')
        context['tag_select'] = tag_select

        # 유저 id를 통해 북마크 정보를 조회
        if user_info := self.request.COOKIES.get('user_info'):
            user, _ = BookmarkModel.objects.get_or_create(user_info=user_info)
            queryset = user.bookmark_webtoon.all()

            if status == "1":
                queryset = user.bookmark_webtoon.filter(webtoon_end=False,
                                                        webtoon_adult=False)
            elif status == "2":
                queryset = user.bookmark_webtoon.filter(webtoon_end=False,
                                                        webtoon_adult=True)
            elif status == "3":
                queryset = user.bookmark_webtoon.filter(
                    webtoon_end=True)
            else:
                queryset = user.bookmark_webtoon.all()

            if tag_select:
                if tag_select != '0':
                    tagquery = TagModel.objects.get(pk=tag_select)
                    queryset = queryset.filter(
                        webtoon_tag=tagquery)
                else:
                    queryset = queryset.all()
            else:
                queryset = user.bookmark_webtoon.all()

            # 검색
            if search := self.request.GET.get('search'):
                context['search'] = search
                queryset = queryset.filter(
                    Q(webtoon_name__icontains=search)).distinct()

            # 페이징
            if page_select := self.request.GET.get('page'):
                paginator = Paginator(queryset, 10)
                page_info = paginator.get_page(page_select)
                context['page_obj'] = page_info
                queryset = page_info.object_list

            context['bookmark'] = queryset
        return context


def bookmark_check(request):
    # 북마크 버튼 누를시 유저 id 에 북마크 기록 저장
    webtoon_id = request.POST.get("bookmark")
    user_info = request.COOKIES.get('user_info')
    method = request.POST.get("check")
    if webtoon_id and user_info:
        webtoon = WebtoonModel.objects.get(pk=webtoon_id)
        user = BookmarkModel.objects.get(user_info=user_info)
        if method == 'true':
            user.bookmark_webtoon.add(webtoon)
        else:
            user.bookmark_webtoon.remove(webtoon)
        user.save()
    return redirect(reverse('webtoon:list'))

webtoon/templates/template/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>
      {% block title %}linktoon : 웹툰을 모아보다 {% endblock %}
    </title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block head %}{% endblock %}
    {% block script_top %} {% endblock %}
</head>
<body>
    <div class="container">
      
        <header>
              <nav >
                  <div class="d-flex pb-2">
                      <a href="{% url 'index' %}" class=" d-flex align-items-center">
                          <img class="" width="50" height="50" role="img" src="{% static 'img/logo/logo.png' %}" alt="">
                      </a>
                      <!--                       
                      아직 개발하지 못한 항목.. 목표하는 서비스의 기능이 아님
                      <ul class="ps-5 nav col-12 col-lg-auto">
                          <li><a href="#" class="nav-link px-2 ">게시판</a></li>
                          <li><a href="#" class="nav-link px-2 ">api</a></li>
                      </ul>
                       -->
                      {% block search %}

                      {% endblock %}
          
                  </div>
          
          
                  <div class="container text-center m-0 ">
                      <div class="row ">
                          <a href="{% url 'webtoon:list' %}" class="col p-1 border border-dark-subtle">웹툰</a>
                          <a href="{% url 'webtoon:bookmark' %}" class="col p-1 border border-dark-subtle">북마크</a>
                      </div>
                  </div>
              </nva>
        </header>
 
      <main class="container">
        {% block nav %}
        {% endblock %}
        
        {% block day %}
        {% endblock %}
        
        {% block publishing %}
        {% endblock %}
        
        {% block tag %}
        {% endblock %}
        
        {% block list %}
        {% endblock %}
        
        {% block page  %}
        {% endblock %}


      </main>


      <footer class="m-1 p-3 pt-5">
        <div >
          <div class="d-flex pb-2">

            <div class="me-5">
              <img class="" width="50" height="50" role="img" src="{% static 'img/logo/logo.png' %}" alt="">
            </div>
            <!-- 모달폼으로 신청을 받아볼예정임
            <div class="m-2 ms-5">
              <a class="me-3" href="#">웹툰 등록 신청</a>
              <a class="me-3" href="#">문의사항</a>
            </div> -->

          </div>

          <div>
            <p>3월 10일 기준으로 연재되는 웹툰 몇개만 모았습니다. 보러가기 클릭시 페이지가 이동됩니다.</p>
            <p></p>
          </div>

        </div>
      </footer>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block script_bottom %} {% endblock %}
</body>
</html>

webtoon/templates/template/day.html
<div class="container text-center p-1 ">
    <div class="row">
        <button type="button" name="day" value="0" class="day col btn 
        {% if day_select == '0' %}
        btn-secondary
        {% else %}
        btn-outline-secondary
        {% endif %}
        border border-dark-subtle" >전체</button>
        
        {% for day in days %}
            {% if day_select == day.day_name %}
            <button type="button" name="day" value="{{ day.day_name }}" class="day col btn btn-secondary border border-dark-subtle" >{{ day.day_name }}</button>
            {% else %}
            <button type="button" name="day" value="{{ day.day_name }}" class="day col btn btn-outline-secondary border border-dark-subtle" >{{ day.day_name }}</button>
            {% endif %}
        {% endfor %}
    </div>
</div>

webtoon/templates/template/nav.html
<div id="main">
    <div class="container text-center p-1">
        <div class="row">
            <button type="button" class="navbut  col btn border border-dark-subtle {% if status == '1' %} btn-secondary {% else %} btn-outline-secondary {% endif %}"
            name="status" value="1">연재</button>

            <button type="button" class="navbut  col btn border border-dark-subtle {% if status == '2' %} btn-secondary {% else %} btn-outline-secondary {% endif %}"
            name="status" value="2">성인</button>
            
            <button type="button" class="navbut  col btn border border-dark-subtle {% if status == '3' %} btn-secondary {% else %} btn-outline-secondary {% endif %}"
            name="status" value="3">완결</button>
    
        </div>
    </div>
</div>

webtoon/templates/template/publishing.html
<div id="publishing" class="">
<div class="container text-center mb-3">
    <div class="row row-cols-auto justify-content-center">
        <button type="button" name="publishing" value="0" class="col border btn btn-outline-secondary rounded-3 m-1 p-1" >전체</button>    
        {% for publishing in publishings %}
            <button type="button" name="publishing" value="{{ publishing.id }}" class="col border btn btn-outline-secondary rounded-3 m-1 p-1" >
                <img class="publishing-logo" src="{{ publishing.publishing_img.url }}" alt="없음">
            </button>    
        {% endfor %}
  
    
    </div>
</div>
</div>

webtoon/templates/template/tag.html
<div id="tag" class="pb-5">
    <div class="container text-center ">
        <div class="row row-cols-auto justify-content-center">
            {% if tag_select == "0" %}
            <button type="button" name="tag" value="0" class="tag col border btn btn-secondary  rounded-3 m-1 p-1" >전체</button>  
            {% else %}
            <button type="button" name="tag" value="0" class="tag col border btn btn-outline-secondary  rounded-3 m-1 p-1" >전체</button>   
            {% endif %}
            {% for tag in tags %} 
                {% if tag_select == tag.id|stringformat:'s' %}
                    <button type="button" name="tag" value="{{ tag.id }}" class="tag col border btn btn-secondary  rounded-3 m-1 p-1" >{{ tag.tag_name }}</button>    
                {% else %}
                    <button type="button" name="tag" value="{{ tag.id }}" class="tag col border btn btn-outline-secondary  rounded-3 m-1 p-1" >{{ tag.tag_name }}</button>    
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>